config/routes.rb
Rails.application.routes.draw do
  # Users routes
  resources :users

  # Authentication
  get "/signup", to: "users#signup_new"
  post "/signup", to: "users#signup_create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  # User routes
  resources :users, except: :new do 
    get "/wishlist", to: "wish_lists#index"
    post "/wishlist", to: "transactions#wishlist_transaction"
  end
  get "/signup", to: "users#new"
  get "/login", to: "users#login"
  resources :categories
  get 'products/show'

  # Categories routes
  resources :categories

  # Products routes
  resources :products do
    post "/cart", to: "shopping_carts#add"
    delete "/cart", to: "shopping_carts#destroy"
    post "/wishlist", to: "wish_lists#add"    
    delete "/wishlist", to: "wish_lists#destroy"
  end
  get "/cart", to: "shopping_carts#index"  

  resources :products do 
    resources :comments, only: [:create, :destroy]
  end

  # Transactions routes
  resources :transactions do
    post "/dispatch", to: "transactions#dispatch_"  
  end

  # Dashboard
  get "/dashboard", to: "dashboards#index"

  # profile
  get "/profile", to: "profiles#index"
  get "/profile/edit", to: "profiles#edit"


  # Application Programming Interface (API)
  namespace :api do
    namespace :v1 do
      resources :keys, only: [:create]
      resources :products, only: [:index, :create, :show, :update, :destroy]
    end
  end

  
  # Root route
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    # Relaciones
    has_many :products, dependent: :destroy

    # Validaciones de Rails
    validates :name, presence: true
    validates :description, presence: true
    validates :image, presence: true

    # Montar uploader
    mount_uploader :image, CategoryImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Relaciones
  belongs_to :user
  belongs_to :product

  # Validaciones
  validates :body, presence: true

end

app/models/product.rb
class Product < ApplicationRecord
    after_initialize :set_default_values
    after_create :post_algolia_product
    after_update :patch_algolia_product
    after_destroy :destroy_algolia_product

    # Relaciones
    belongs_to :category
    validates :category, presence: true
    has_many :shopping_cart_products, dependent: :destroy
    has_many :shopping_carts, through: :shopping_cart_products
    has_many :comments, dependent: :destroy
    has_many :wish_list_products, dependent: :destroy
    has_many :wish_lists, through: :wish_list_products    

    # Validaciones de Rails
    validates :category, presence: true
    validates :sku, presence: true, uniqueness: true
    validates :name, presence: true
    validates :description, presence: true
    validates :image, presence: true
    validates :price, presence: true, numericality: { greater_than: 0 }
    validates :jumbotron_image, presence: true, if: :jumbotron?

    # Montar uploader
    mount_uploader :image, ProductImageUploader
    mount_uploader :jumbotron_image, JumbotronImageUploader

    private

    def set_default_values
        self.jumbotron ||= false
    end

    def post_algolia_product
        AlgoliaPostProductJob.perform_later self
    end

    def patch_algolia_product
        AlgoliaPatchProductJob.perform_later self
    end

    def destroy_algolia_product
        AlgoliaDestroyProductJob.perform_later self
    end
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user
  has_many :shopping_cart_products
  has_many :products, through: :shopping_cart_products
  has_one :shopping_cart_transaction, :class_name => "Transaction"
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  after_initialize :default_values

  belongs_to :user
  belongs_to :shopping_cart

  def default_values
    self.dispatched = false if self.dispatched.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
    # Relaciones 
    has_many :comments, :dependent => :delete_all
    has_many :user_keys, :dependent => :delete_all
    
    # Manejar de la misma manera tEST@example.com y test@example.com
    before_save { self.email = email.downcase }

    # Relaciones
    has_many :transactions, :dependent => :delete_all
    has_many :shopping_carts, :dependent => :delete_all
    has_one :wish_list

    # Declaración de roles
    enum role: { "admin" => 0, "user" => 1}, _suffix: true
    validates :role, presence: true

    # Validaciones de Rails
    validates :email, presence: true,
        format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
        uniqueness: { case_sensitive: false }
    
    validates :first_name, presence: true
    validates :last_name, presence: true
    
    # Contraseñas
    has_secure_password
    validates :password, presence: true

    # Avatar
    mount_uploader :avatar, UserAvatarUploader
end

app/models/user_key.rb
class UserKey < ApplicationRecord
  belongs_to :user
end

app/models/wish_list.rb
class WishList < ApplicationRecord
  belongs_to :user
  has_many :wish_list_products
  has_many :products, through: :wish_list_products
end

app/models/wish_list_product.rb
class WishListProduct < ApplicationRecord
  belongs_to :wish_list
  belongs_to :product
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @jumbotron_products = Product.where jumbotron: true
    @categories = Category.all
  end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
    # Usuario debe estar autenticado.
    before_action :authenticate
    before_action :set_shopping_cart
    before_action :set_product, only: [:add, :destroy]

    def add
        respond_to do |format|
            if @shopping_cart.products << @product
                format.html {redirect_to @product, notice: "Producto agregado exitosamente a carro de compras."}
                format.js
            else
                format.html {redirect_to @product, notice: "Producto no pudo ser agregado al carro de compras."}
            end
        end
    end

    def destroy
        respond_to do |format|
            if @shopping_cart.products.delete(@product)
                format.html {redirect_to cart_url, notice: "Producto eliminado del carro de compras."}
                format.js
            end
        end
    end

    def index
    end

    private

    def set_product
        @product = Product.find(params[:product_id])
    end

    def set_shopping_cart
        def has_active_cart(cart)
            cart.each do |s_cart|
                if !(s_cart.reserved)
                    return true
                end
            end     
            return false 
        end

        def get_id(array)
            array.each do |cart|
                if !(cart.reserved)
                    return cart.id                    
                end
            end
        end

        cart_array = current_user.shopping_carts.to_ary()
        if has_active_cart(cart_array)            
            not_reserved_cart_id = get_id(cart_array)
            @shopping_cart = current_user.shopping_carts.find(not_reserved_cart_id)
        else
            @shopping_cart = current_user.shopping_carts.create!( attributes = {reserved: false, user_id: current_user.id})
        end

    end     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wish_list_helper.rb
module WishListHelper
end

app/views/shopping_carts/add.js.erb
var content = $("<%=j render :partial => 'layouts/notice', :locals => {:notice => "Producto agregado exitosamente a carro de compras."}%>");
$('#site-navigation').after(content);
content.delay(1500).slideUp();
<%
def get_id(array)
    array.each do |cart|
        if !(cart.reserved)
            return cart.id                    
        end
    end
end
%>

$('#shopping-cart-number').text("<%= shopping_cart_number %>");

app/views/shopping_carts/destroy.js.erb
$('.cart-counter').text("Carro de compras " + <%= current_user.shopping_carts.find(get_id(current_user.shopping_carts.to_a)).products.count.to_s%>);

app/views/shopping_carts/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-6">
            <h1>Carro de compras</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-8" id="cart-products-list">
            <% if @shopping_cart.products.length > 0 %>
                <table>
                <thead>
                    <tr>
                        <th>SKU</th>
                        <th>Categoría</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    <% @shopping_cart.products.each do |product| %>
                    <tr>
                        <td><%= product.sku %></td>
                        <td><%= product.category.name %></td>
                        <td><%= product.name %></td>
                        <td><%= product.price %></td>
                        <td><%= link_to fa_icon("search", text: "Ver"), product_path(product), class: "button" %></td>
                        <td><%= link_to fa_icon("trash", text: "Eliminar del carro"), product_cart_path(product), data: { :confirm => "¿Estás seguro que deseas eliminar este producto del carro de compras?" }, remote: true, :method => :delete, class: "button" %></td>
                    </tr>
                    <% end %>
                </tbody>
                </table>
            <% else %>
                <h3>No tienes productos en tu carro de compras.</h3>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            <td><%= link_to fa_icon("beer", text: "Reservar"), transactions_path(shopping_cart_id: @shopping_cart.id, user_id:current_user.id), class: "button", :method => :post %></td>
        </div>
    </div>
</div>