config/routes.rb
Rails.application.routes.draw do
  # Users routes
  resources :users

  # Authentication
  get "/signup", to: "users#signup_new"
  post "/signup", to: "users#signup_create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  # User routes
  resources :users, except: :new do 
    get "/wishlist", to: "wish_lists#index"
    post "/wishlist", to: "transactions#wishlist_transaction"
  end
  get "/signup", to: "users#new"
  get "/login", to: "users#login"
  resources :categories
  get 'products/show'

  # Categories routes
  resources :categories

  # Products routes
  resources :products do
    post "/cart", to: "shopping_carts#add"
    delete "/cart", to: "shopping_carts#destroy"
    post "/wishlist", to: "wish_lists#add"    
    delete "/wishlist", to: "wish_lists#destroy"
  end
  get "/cart", to: "shopping_carts#index"  

  resources :products do 
    resources :comments, only: [:create, :destroy]
  end

  # Transactions routes
  resources :transactions do
    post "/dispatch", to: "transactions#dispatch_"  
  end

  # Dashboard
  get "/dashboard", to: "dashboards#index"

  # profile
  get "/profile", to: "profiles#index"
  get "/profile/edit", to: "profiles#edit"


  # Application Programming Interface (API)
  namespace :api do
    namespace :v1 do
      resources :keys, only: [:create]
      resources :products, only: [:index, :create, :show, :update, :destroy]
    end
  end

  
  # Root route
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    # Relaciones
    has_many :products, dependent: :destroy

    # Validaciones de Rails
    validates :name, presence: true
    validates :description, presence: true
    validates :image, presence: true

    # Montar uploader
    mount_uploader :image, CategoryImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Relaciones
  belongs_to :user
  belongs_to :product

  # Validaciones
  validates :body, presence: true

end

app/models/product.rb
class Product < ApplicationRecord
    after_initialize :set_default_values
    after_create :post_algolia_product
    after_update :patch_algolia_product
    after_destroy :destroy_algolia_product

    # Relaciones
    belongs_to :category
    validates :category, presence: true
    has_many :shopping_cart_products, dependent: :destroy
    has_many :shopping_carts, through: :shopping_cart_products
    has_many :comments, dependent: :destroy
    has_many :wish_list_products, dependent: :destroy
    has_many :wish_lists, through: :wish_list_products    

    # Validaciones de Rails
    validates :category, presence: true
    validates :sku, presence: true, uniqueness: true
    validates :name, presence: true
    validates :description, presence: true
    validates :image, presence: true
    validates :price, presence: true, numericality: { greater_than: 0 }
    validates :jumbotron_image, presence: true, if: :jumbotron?

    # Montar uploader
    mount_uploader :image, ProductImageUploader
    mount_uploader :jumbotron_image, JumbotronImageUploader

    private

    def set_default_values
        self.jumbotron ||= false
    end

    def post_algolia_product
        AlgoliaPostProductJob.perform_later self
    end

    def patch_algolia_product
        AlgoliaPatchProductJob.perform_later self
    end

    def destroy_algolia_product
        AlgoliaDestroyProductJob.perform_later self
    end
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user
  has_many :shopping_cart_products
  has_many :products, through: :shopping_cart_products
  has_one :shopping_cart_transaction, :class_name => "Transaction"
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  after_initialize :default_values

  belongs_to :user
  belongs_to :shopping_cart

  def default_values
    self.dispatched = false if self.dispatched.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
    # Relaciones 
    has_many :comments, :dependent => :delete_all
    has_many :user_keys, :dependent => :delete_all
    
    # Manejar de la misma manera tEST@example.com y test@example.com
    before_save { self.email = email.downcase }

    # Relaciones
    has_many :transactions, :dependent => :delete_all
    has_many :shopping_carts, :dependent => :delete_all
    has_one :wish_list

    # Declaración de roles
    enum role: { "admin" => 0, "user" => 1}, _suffix: true
    validates :role, presence: true

    # Validaciones de Rails
    validates :email, presence: true,
        format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
        uniqueness: { case_sensitive: false }
    
    validates :first_name, presence: true
    validates :last_name, presence: true
    
    # Contraseñas
    has_secure_password
    validates :password, presence: true

    # Avatar
    mount_uploader :avatar, UserAvatarUploader
end

app/models/user_key.rb
class UserKey < ApplicationRecord
  belongs_to :user
end

app/models/wish_list.rb
class WishList < ApplicationRecord
  belongs_to :user
  has_many :wish_list_products
  has_many :products, through: :wish_list_products
end

app/models/wish_list_product.rb
class WishListProduct < ApplicationRecord
  belongs_to :wish_list
  belongs_to :product
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @jumbotron_products = Product.where jumbotron: true
    @categories = Category.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_admin, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /signup
  def signup_new
    @user = User.new
  end

  # POST /signup
  def signup_create
    @user = User.new(user_params)

    if @user.save
      UserMailer.signup_email(@user).deliver_later
      redirect_to "/login", notice: "Usuario creado exitosamente."
    else
      render :signup_new
    end
  end
  

  # GET /users 
  def index
    @users = User.all
  end

  # GET /users/1 
  def show        
  end

  def new 
    @user = User.new  
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuario creado exitosamente.' }        
      else
        format.html { render :new }        
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Usuario actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Usuario eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :email,
        :role,
        :password,
        :password_confirmation,
        :avatar
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wish_list_helper.rb
module WishListHelper
end

app/views/users/_form.html.erb
<%= simple_form_for user do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :role %>
  <%= f.input :avatar, as: :file %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit %>
<% end %>

app/views/users/_signup_form.html.erb
<%= simple_form_for user, url: "/signup" do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.input :role %>
  <%= f.input :avatar, as: :file %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit %>
<% end %>

app/views/users/edit.html.erb
<div class="container" id="edit-user-container">
    <div class="row">
        <div class="col-6 col-offset-3">
            <div class="panel">
                <div class="panel-heading">
                    <h2>Editar usuario</h2>
                </div>
                <div class="panel-body">
                    <%= render "form", user: @user %>
                </div>
                <%= link_to "Mostrar usuario", @user %>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-6">
            <h1>Usuarios</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-8">
            <% if @users.length > 0 %>
                <table>
                <thead>
                    <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Email</th>
                    <th>Rol</th>
                    </tr>
                </thead>

                <tbody>
                    <% @users.each do |user| %>
                    <tr>
                        <td> <%= user.first_name %> </td>
                        <td> <%= user.last_name %> </td>
                        <td> <%= user.email %> </td>
                        <td> <%= user.role %> </td>
                        <td> <%= link_to fa_icon("search", text: "Ver usuario"), user_path(user), class: "button"%> </td>
                        <td> <%= link_to fa_icon("edit", text: "Editar usuario"), edit_user_path(user), class: "button"%> </td>
                        <td> <%= link_to fa_icon("trash", text: "Eliminar usuario"), user_path(user), data: { :confirm => "¿Estás seguro que deseas eliminar el usuario?" }, :method => :delete, class: "button"%> </td>
                    </tr>
                    <% end %>
                </tbody>
                </table>
            <% else %>
                <h3>Aún no hay usuarios registrados.</h3>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <%= link_to fa_icon("plus", text: "Crear usuario"), new_user_path, class: "button" %>
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div class="container" id="new-create-user-container">
    <div class="row">
        <div class="col-6 col-offset-3">
            <div class="panel">
                <div class="panel-heading">
                    <h2>Crear usuario</h2>
                </div>
                <div class="panel-body">
                    <%= render 'form', user: @user %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-6">
            <h1>Detalle del usuario</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <ul>
                <li> <strong>Nombre: </strong> <%=@user.first_name %> </li>
                <li> <strong>Apellido: </strong> <%= @user.last_name %> </li>
                <li> <strong>Email: </strong> <%= @user.email %> </li>
                <li> <strong>Rol: </strong> <%= @user.role %> </li>
                <li> <%= link_to fa_icon("pencil", text: "Editar usuario"), edit_user_path(@user), class: "button"%> </li> 
                <li> <%= link_to fa_icon("trash", text: "Eliminar usuario"), user_path(@user), data: { :confirm => "¿Estás seguro que deseas eliminar el usuario?" }, :method => :delete, class: "button"%></li>
            </ul>
        </div>        
    </div>
</div>

app/views/users/signup_new.html.erb
<div class="container" id="new-user-container">
    <div class="row">
        <div class="col-6 col-offset-3">
            <div class="panel">
                <div class="panel-heading">
                    <h2>Registrarse en el sistema</h2>
                </div>
                <div class="panel-body">
                    <%= render 'signup_form', user: @user %>
                </div>
            </div>
        </div>
    </div>
</div>