config/routes.rb
Rails.application.routes.draw do
  # Users routes
  resources :users

  # Authentication
  get "/signup", to: "users#signup_new"
  post "/signup", to: "users#signup_create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  # User routes
  resources :users, except: :new do 
    get "/wishlist", to: "wish_lists#index"
    post "/wishlist", to: "transactions#wishlist_transaction"
  end
  get "/signup", to: "users#new"
  get "/login", to: "users#login"
  resources :categories
  get 'products/show'

  # Categories routes
  resources :categories

  # Products routes
  resources :products do
    post "/cart", to: "shopping_carts#add"
    delete "/cart", to: "shopping_carts#destroy"
    post "/wishlist", to: "wish_lists#add"    
    delete "/wishlist", to: "wish_lists#destroy"
  end
  get "/cart", to: "shopping_carts#index"  

  resources :products do 
    resources :comments, only: [:create, :destroy]
  end

  # Transactions routes
  resources :transactions do
    post "/dispatch", to: "transactions#dispatch_"  
  end

  # Dashboard
  get "/dashboard", to: "dashboards#index"

  # profile
  get "/profile", to: "profiles#index"
  get "/profile/edit", to: "profiles#edit"


  # Application Programming Interface (API)
  namespace :api do
    namespace :v1 do
      resources :keys, only: [:create]
      resources :products, only: [:index, :create, :show, :update, :destroy]
    end
  end

  
  # Root route
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    # Relaciones
    has_many :products, dependent: :destroy

    # Validaciones de Rails
    validates :name, presence: true
    validates :description, presence: true
    validates :image, presence: true

    # Montar uploader
    mount_uploader :image, CategoryImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Relaciones
  belongs_to :user
  belongs_to :product

  # Validaciones
  validates :body, presence: true

end

app/models/product.rb
class Product < ApplicationRecord
    after_initialize :set_default_values
    after_create :post_algolia_product
    after_update :patch_algolia_product
    after_destroy :destroy_algolia_product

    # Relaciones
    belongs_to :category
    validates :category, presence: true
    has_many :shopping_cart_products, dependent: :destroy
    has_many :shopping_carts, through: :shopping_cart_products
    has_many :comments, dependent: :destroy
    has_many :wish_list_products, dependent: :destroy
    has_many :wish_lists, through: :wish_list_products    

    # Validaciones de Rails
    validates :category, presence: true
    validates :sku, presence: true, uniqueness: true
    validates :name, presence: true
    validates :description, presence: true
    validates :image, presence: true
    validates :price, presence: true, numericality: { greater_than: 0 }
    validates :jumbotron_image, presence: true, if: :jumbotron?

    # Montar uploader
    mount_uploader :image, ProductImageUploader
    mount_uploader :jumbotron_image, JumbotronImageUploader

    private

    def set_default_values
        self.jumbotron ||= false
    end

    def post_algolia_product
        AlgoliaPostProductJob.perform_later self
    end

    def patch_algolia_product
        AlgoliaPatchProductJob.perform_later self
    end

    def destroy_algolia_product
        AlgoliaDestroyProductJob.perform_later self
    end
end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user
  has_many :shopping_cart_products
  has_many :products, through: :shopping_cart_products
  has_one :shopping_cart_transaction, :class_name => "Transaction"
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  after_initialize :default_values

  belongs_to :user
  belongs_to :shopping_cart

  def default_values
    self.dispatched = false if self.dispatched.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
    # Relaciones 
    has_many :comments, :dependent => :delete_all
    has_many :user_keys, :dependent => :delete_all
    
    # Manejar de la misma manera tEST@example.com y test@example.com
    before_save { self.email = email.downcase }

    # Relaciones
    has_many :transactions, :dependent => :delete_all
    has_many :shopping_carts, :dependent => :delete_all
    has_one :wish_list

    # Declaración de roles
    enum role: { "admin" => 0, "user" => 1}, _suffix: true
    validates :role, presence: true

    # Validaciones de Rails
    validates :email, presence: true,
        format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
        uniqueness: { case_sensitive: false }
    
    validates :first_name, presence: true
    validates :last_name, presence: true
    
    # Contraseñas
    has_secure_password
    validates :password, presence: true

    # Avatar
    mount_uploader :avatar, UserAvatarUploader
end

app/models/user_key.rb
class UserKey < ApplicationRecord
  belongs_to :user
end

app/models/wish_list.rb
class WishList < ApplicationRecord
  belongs_to :user
  has_many :wish_list_products
  has_many :products, through: :wish_list_products
end

app/models/wish_list_product.rb
class WishListProduct < ApplicationRecord
  belongs_to :wish_list
  belongs_to :product
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authorize_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  def index 
    @categories = Category.all       
  end

  # GET /categories/new
  def new
    @category = Category.new
  end
  
  # GET /categories/:id
  def show    
  end

  # POST /categories
  def create
    @category = Category.new(category_params)
  
    if @category.save
      redirect_to @category, notice: "Categoría creada exitosamente."
    else
      render :new
    end
  end

  # GET /categories/:id/edit
  def edit
  end

  # PATCH /categories/:id
  def update
    if @category.update(category_params)
      redirect_to @category, notice: "Categoría actualizada exitosamente."
    else
      render :edit
    end
  end

  # DELETE /categories/:id
  def destroy
    @category.destroy
    redirect_to categories_path, notice: "Categoría eliminada exitosamente."
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(
        :name,
        :description,
        :image
      )
    end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @jumbotron_products = Product.where jumbotron: true
    @categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wish_list_helper.rb
module WishListHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for category do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :image, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-6 col-offset-3">
            <div class="panel">
                <div class="panel-heading">
                    <h2>Editar categoría</h2>
                </div>
                <div class="panel-body">
                    <%= render 'form', category: @category %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-6 h1-margin">
            <h1>Categorías</h1>
            <% if current_user && current_user.admin_role? %>
                <div class="row">
                    <div class="col-12">
                        <%= link_to fa_icon("plus", text: "Crear categoría"), new_category_path, class: "button" %>
                    </div>
                </div>
            <% end %>
        </div>        
    </div>
    <br>
    <div class="row">
        <div class="col-8">
            <% if @categories.length > 0 %>
                <div class="categories-container">
                    <% @categories.each do |category| %>
                        <div class="category">
                            <div class="category-row">
                                <div class="category-image-container">
                                    <%= image_tag category.image, :class => "category-image" %>
                                </div>
                                <div class="category-description">
                                    <h4> <%= category.name %> </h4>                                
                                    <%= category.description %>
                                </div>
                            </div>
                            <div class="row">
                                <%= link_to fa_icon("search"), category_path(category) %>
                                <% if current_user && current_user.admin_role? %>
                                    <%= link_to fa_icon("pencil"), edit_category_path(category) %>
                                    <%= link_to fa_icon("trash"), category_path(category), data: { :confirm => "¿Estás seguro que deseas eliminar la categoría?" }, :method => :delete %> 
                                <% end %>
                            </div>
                        </div>
                    <% end %>
                </div>
            <% else%>
                <h3>Aún no hay categorías en el sistema.</h3>
            <% end %>
        </div>
    </div>
</div>

app/views/categories/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-6 col-offset-3">
            <div class="panel">
                <div class="panel-heading">
                    <h2>Crear nueva categoria </h2>
                </div>
                <div class="panel-body">
                    <%= render 'form', category: @category %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-6">
            <h3>Detalle de la categoria</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <ul>
                <li> <strong>Nombre: </strong> <%=@category.name %> </li>
                <li> <strong>Descripcion: </strong> <%= @category.description %> </li>
                <% if current_user && current_user.admin_role? %>
                    <li> <%= link_to fa_icon("pencil", text: "Editar categoria"), edit_category_path(@category), class: "button"%> </li> 
                    <li> <%= link_to fa_icon("trash", text: "Eliminar categoria"), category_path(@category), data: { :confirm => "¿Estás seguro que deseas eliminar la categoría?" }, :method => :delete, class: "button"%> </li> 
                <% end %>
            </ul>
        </div>        
    </div>
    <hr />
    <div class="row">
        <div class="col-6">
            <h3>Productos</h3>
        </div>
    </div>
    <%= render "products/product_list", products: @category.products, is_transaction: false %>
</div>