config/routes.rb
Rails.application.routes.draw do
  # Users routes
  resources :users

  # Authentication
  get "/signup", to: "users#signup_new"
  post "/signup", to: "users#signup_create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  # User routes
  resources :users, except: :new do 
    get "/wishlist", to: "wish_lists#index"
    post "/wishlist", to: "transactions#wishlist_transaction"
  end
  get "/signup", to: "users#new"
  get "/login", to: "users#login"
  resources :categories
  get 'products/show'

  # Categories routes
  resources :categories

  # Products routes
  resources :products do
    post "/cart", to: "shopping_carts#add"
    delete "/cart", to: "shopping_carts#destroy"
    post "/wishlist", to: "wish_lists#add"    
    delete "/wishlist", to: "wish_lists#destroy"
  end
  get "/cart", to: "shopping_carts#index"  

  resources :products do 
    resources :comments, only: [:create, :destroy]
  end

  # Transactions routes
  resources :transactions do
    post "/dispatch", to: "transactions#dispatch_"  
  end

  # Dashboard
  get "/dashboard", to: "dashboards#index"

  # profile
  get "/profile", to: "profiles#index"
  get "/profile/edit", to: "profiles#edit"


  # Application Programming Interface (API)
  namespace :api do
    namespace :v1 do
      resources :keys, only: [:create]
      resources :products, only: [:index, :create, :show, :update, :destroy]
    end
  end

  
  # Root route
  root "home#index"
end

app/models/product.rb
class Product < ApplicationRecord
    after_initialize :set_default_values
    after_create :post_algolia_product
    after_update :patch_algolia_product
    after_destroy :destroy_algolia_product

    # Relaciones
    belongs_to :category
    validates :category, presence: true
    has_many :shopping_cart_products, dependent: :destroy
    has_many :shopping_carts, through: :shopping_cart_products
    has_many :comments, dependent: :destroy
    has_many :wish_list_products, dependent: :destroy
    has_many :wish_lists, through: :wish_list_products    

    # Validaciones de Rails
    validates :category, presence: true
    validates :sku, presence: true, uniqueness: true
    validates :name, presence: true
    validates :description, presence: true
    validates :image, presence: true
    validates :price, presence: true, numericality: { greater_than: 0 }
    validates :jumbotron_image, presence: true, if: :jumbotron?

    # Montar uploader
    mount_uploader :image, ProductImageUploader
    mount_uploader :jumbotron_image, JumbotronImageUploader

    private

    def set_default_values
        self.jumbotron ||= false
    end

    def post_algolia_product
        AlgoliaPostProductJob.perform_later self
    end

    def patch_algolia_product
        AlgoliaPatchProductJob.perform_later self
    end

    def destroy_algolia_product
        AlgoliaDestroyProductJob.perform_later self
    end
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::V1::BaseController
    before_action :authenticate_user!, only: [:create, :update, :destroy]
    before_action :set_product, only: [:show, :update, :destroy]

    def index
        products = Product.all
        render(json: products.to_json)
    end

    def create
        if @current_user.admin_role?
            @product = Product.new(product_params)
            if @product.save
                head :created, location: @product
            else
                head :internal_server_error
            end
        else
            head :unauthorized
        end
    end

    def update
        if @current_user.admin_role?
            if @product.update(product_params)
                head :ok, location: @product
            else
                head :internal_server_error
            end
        else
            head :unauthorized
        end
    end

    def destroy
        if @current_user.admin_role?
            if @product.destroy
                head :ok
            else
                head :internal_server_error
            end
        else
            head :unauthorized
        end
    end

    def show
        render(json: @product.to_json)
    end

    private

    def set_product
        @product = Product.find(params[:id])
    end

    def product_params
        params.require(:product).permit(
        :sku,
        :name,
        :description,
        :image,
        :price,
        :category_id,
        :jumbotron,
        :jumbotron_image
        )
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authorize_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # POST /products
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: "El producto fue creado exitosamente."
    else
      render :new
    end
  end

  # GET /products/:id
  def show
    @comment = Comment.new
    @comments = @product.comments
  end

  # GET /products/:id/edit
  def edit
  end

  # PATCH /products/:id
  def update
    if @product.update(product_params)
      redirect_to @product, notice: "El producto fue actualizado exitosamente."
    else
      render :edit
    end
  end

  # DELETE /products/:id
  def destroy
    @product.destroy
    redirect_to products_path, notice: "El producto fue eliminado correctamente."
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(
      :sku,
      :name,
      :description,
      :image,
      :price,
      :category_id,
      :jumbotron,
      :jumbotron_image
    )
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_comment_form.html.erb
<%= simple_form_for [@product, @comment], remote: true do |f| %> 
    <%= f.text_area :body, :cols => "40", :rows => "8" %>
    <%= f.button :submit %>
<% end %>

app/views/products/_comment_table.html.erb
<div class="comment" id=<%= product.id %>>
    <% comments.each do |comment| %>
    <div class="comment-container">
        <div class="row">
            <div class="comment-user"><%= comment.user.first_name + " " + comment.user.last_name%></div>
            <div class="comment-date">
                <%= comment.created_at %>
                <% if current_user && current_user.admin_role? %>
                    <%= link_to fa_icon("trash"), product_comment_path(product, comment), remote: true, data: { :confirm => "¿Estás seguro que deseas eliminar este comentario?" }, :method => :delete, class: "trash-button" %>
                <% end %>
            </div>
        </div>
        <div class="comment-body"><%= comment.body %></div>
        <div class="row">
            
        </div>
    </div>
    <% end %>
</div>

app/views/products/_form.html.erb
<%= simple_form_for product do |f| %>
    <%= f.input :sku %>
    <%= f.association :category %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :image, as: :file %>
    <%= f.input :jumbotron %>
    <%= f.input :jumbotron_image, as: :file %>
    <%= f.button :submit %>
<% end %>

app/views/products/_product_list.html.erb
<div class="row">
    <% if products.length > 0 %>
        <% products.each do |product| %>
        <div class="featured-product col-2">
            <h4><%= link_to product.name, product_path(product) %></h4>
            <p class="text-center">
                <%= link_to image_tag(product.image.url), product_path(product) %>
                <strong>Precio:</strong> <%= number_to_currency(product.price) %> <br />
                <% if !(is_transaction) %>
                    <%= link_to fa_icon("search", text: "Ver"), product_path(product), class: "button" %>
                <% end %>
                <% if current_user %>
                    <br />
                    <% if !(is_transaction)%>
                        <%= link_to fa_icon("cart-plus", text: "Carro"), product_cart_path(product), class: "button", remote: true, :method => :post %> <br />
                        <%= link_to fa_icon("gift", text: "Wishlist"), product_wishlist_path(product), class: "button", :method => :post %>
                        <% if current_user.admin_role? %>
                            <br />
                            <%= link_to fa_icon("pencil", text: "Editar"), edit_product_path(product), class: "button" %> <br />
                            <%= link_to fa_icon("trash", text: "Eliminar"), product_path(product), data: { :confirm => "¿Estás seguro que deseas eliminar este producto?" }, :method => :delete, class: "button" %>
                        <% end %>
                    <% end %>
                <% end %>
            </p>
        </div>
        <% end %>
    <% else %>
        <h3 class="col-12">No hay productos disponibles.</h3>
    <% end %>
</div>

app/views/products/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-6 col-offset-3">
            <div class="panel">
                <div class="panel-heading">
                    <h2>Editar producto</h2>
                </div>
                <div class="panel-body">
                    <%= render "form", product: @product %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/products/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-6">
            <h1>Productos</h1>
        </div>
    </div>
    <%= render "product_list", products: @products, is_transaction: false %>
    <% if current_user && current_user.admin_role? %>
    <div class="row">
        <div class="col-12">
            <%= link_to fa_icon("plus", text: "Crear producto"), new_product_path, class: "button" %>
        </div>
    </div>
    <% end %>
</div>

app/views/products/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-6 col-offset-3">
            <div class="panel">
                <div class="panel-heading">
                    <h2>Crear producto</h2>
                </div>
                <div class="panel-body">
                    <%= render "form", product: @product %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/products/show.html.erb
 <div class="container">
    <div class="row">
        <h1 class="text-margin"><%= @product.name %></h1>
    </div>
    <div class="row" id="first-row">
        <div class="col-2">
            <h5><strong>Precio:</strong> <%= number_to_currency(@product.price) %></h5>
            <h5><strong>Categoría:</strong> <%= link_to @product.category.name, category_path(@product.category) %></h5>
        </div>
        <% if current_user %>
        <div class="col-4">
            <% if current_user.admin_role? %>
                <%= link_to fa_icon("pencil", text: "Editar"), edit_product_path(@product), class: "button" %>
                <%= link_to fa_icon("trash", text: "Eliminar"), product_path(@product), data: { :confirm => "¿Estás seguro que deseas eliminar el producto?" }, :method => :delete, class: "button" %>
            <% end %>
            <%= link_to fa_icon("cart-plus", text: "Carro"), product_cart_path(@product), class: "button", :method => :post, remote: true %> 
            <%= link_to fa_icon("gift", text: "Wishlist"), product_wishlist_path(@product), class: "button", :method => :post %>
        </div>
        <% end %>
    </div>
    <div class="row">
        <div class="col-2">
            <%= image_tag @product.image.url, :class => "product-image image-margin" %>
        </div>
        <div class="col-10">
            <p class="text-margin">                 
                <%= @product.description %>
            </p>
        </div>        
    </div>
    <hr />
    <div class="row">
        <div class="col-4">
            <h4>Comentarios</h4>
        </div>
    </div>
    <div class="row">
        <div class="col-8" id="comment-space">
        <% if @comments.length > 0 %>
            <%= render "comment_table", product: @product, comments: @comments%>
        <% else %>
            <h4>Aún no hay comentarios.</h4>
        <% end %>
        </div>
    </div>
    <% if current_user %>
    <br>
    <div class="row">
        <div class="col-10">
            <%= render "comment_form", comment: @comment %>
        </div>
    </div>
    <% end %>
</div>